### ISSUE TITLE
nodejs version and packages well out-of-date

### ISSUE THREAD

**Issue by ghost** [humboldt123/mutuals#2]
nodejs version and packages well out-of-date, and need to be updated to ensure security and stability

**Comment by humboldt123** [comment]
The NodeJS version isn't explicitly listed in `package.json`. I did update axios since that package was behind by one major version but the rest of the packages have carets in front of their version number and should find the latest minor version automatically.

Works on Windows 10, NodeJS v18.12.1 as of now.

**Comment by ghost** [comment]
LGTM!
